{{- if .Values.logstashPipeline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.logstashPipeline }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}

{{- if .Values.logstashPipelineFiles }}
{{- range $path, $_ := .Files.Glob .Values.logstashPipelineFiles }}
  {{ base $path }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end -}}
{{- end -}}

{{- end -}}
